#!/usr/bin/env python3
"""Generate documentation and playground source panels from compiler-checked source regions."""
from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parent.parent
SOURCES = {
    "Android": ("kotlin", ROOT / "android/playground/src/main/kotlin/dev/trail/playground/examples/IntegrationExamples.kt"),
}
TITLES = {
    "loading-route": "Loading arc to directions route",
    "setup": "Demo geometry", "preset": "Named preset", "basic": "Render a preset",
    "runtime-color": "Runtime color", "plugin": "Custom style and animation", "playback": "Playback controls",
    "sequence": "Ordered animation steps", "layers": "Independent layers", "google-maps": "Google Maps Compose",
    "android-view": "Android View", "mapkit": "MapKit convenience host",
    "existing-swiftui-map": "Existing SwiftUI Map", "existing-mkmapview": "Existing MKMapView",
    "geographic-routes": "Real coordinates: route, direct, arc and great circle",
    "custom-map-adapter": "Provider-neutral overlay contract",
}

def regions(source):
    found = re.findall(r"// example:start ([\w-]+)\n(.*?)// example:end \1", source, re.S)
    result = dict(found)
    assert len(found) == len(result) and len(found) == source.count("// example:start "), "Malformed or duplicate example region"
    return {name: text.rstrip() + "\n" for name, text in result.items()}

def outputs():
    for platform, (language, path) in SOURCES.items():
        parts = regions(path.read_text())
        imports = "\n".join(line for line in path.read_text().splitlines() if line.startswith("import ")) + "\n"
        document = f"# {platform} — compiled integration examples\n\n"
        document += "Generated by `scripts/sync-examples.py`; edit the source file, then regenerate. These examples compile in the playground application.\n\n"
        document += f"Source: [{path.name}](../../{path.relative_to(ROOT)}).\n\n"
        document += "Use the shared geometry and named preset below. Map examples require their platform adapter; the plugin example imports the separately compiled sample plugin. The setup includes sample-app imports; ordinary core/Canvas consumers need only the modules they use.\n\n"
        document += f"## Imports\n\n```{language}\n{imports}```\n\n"
        for name, content in parts.items():
            document += f"## {TITLES[name]}\n\n```{language}\n{content}```\n\n"
            if name in ("setup", "preset", "geographic-routes", "custom-map-adapter"):
                continue
            code = parts["preset"] + "\n" + content if name in ("basic", "playback", "google-maps", "android-view", "mapkit", "existing-swiftui-map", "existing-mkmapview") else content
            note = "// Shared demo geometry and imports: see the compiled IntegrationExamples source.\n\n"
            output = ROOT / f"android/playground/src/main/assets/examples/{name}.txt"
            yield output, note + code
        yield ROOT / f"docs/examples/{platform}.md", document.rstrip() + "\n"

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, expected in outputs():
        if args.check:
            if not path.exists() or path.read_text() != expected:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected)
    if stale:
        raise SystemExit("Stale examples; run scripts/sync-examples.py:\n" + "\n".join(stale))
    print("Example source, docs, and playground panels are in sync.")

if __name__ == "__main__":
    main()
